### ISSUE TITLE
Abstract interface

### ISSUE THREAD

**Issue by hexaeder** [PIK-ICoNe/ProBeTune.jl#1]
Yesterday we had a talk about a possible more abstract interface to `ProBeTune`. I had a look throuth the code and came up with the following suggestion:

## `AbstractPBTproblem`
The new high level problem definition would be
```julia
"""
    AbstractPBTProblem

Supertype type to define PBTProblems.

Each concrete subtype has to have the fields
- p::PBTProblemParameters
- input_sampler::AbstractInputSampler

Each concrete subtype has to implement

    solve_sys_spec(pbt::ConcretePBTProblem, input, p_sys, p_spec) -> sol_sys, sol_spec

which returns a tuple of two DiffEq solution objects: one for the sys, one for the spec.
"""
abstract type AbstractPBTProblem end
```
I've introduced the `PBTProblemParameters` type to avoid heavy repetition of fields in differen subtypes.
```julia
"""
    mutabel struct PBTProblemParameters

Fields:
- `N_samples::Int`: Number of samples to use.
- `size_p_spec::Int`: Size of the parameter space of the spec.
- `size_p_sys::Int`: Size of the parameter space of the system.
- `output_metric`: Metric that calculates how far the outputs of system and spec are apart.
    Called as `output_metric(sol_system, sol_spec)`, where sol is a DifferentialEquations solution object.
"""
mutable struct PBTProblemParameters
    N_samples::Int
    size_p_spec::Int
    size_p_sys::Int
    output_metric
end
```

## input sampling
Additional to what we've talked about yesterday I think it might be also a good idea to also introduce a more abstract interface to the `inputs`. I think not all inputs are best represented as a function `(t) -> input`. But I am not sure whether this is really neccessary. However this is what I came up with:

```julia
"""
    abstract type AbstractInputSampler end

Abstract type for all `PBTSamplers`. Each concret type musst implement

    `Base.getindex(sampler::ConcreteSamplerType, i)`

to get the i-th input sample.
"""
abstract type AbstractInputSampler end
```

One thing I added which I think would be quite imporant is to pass an RNG to the sampler function. Otherwise the computation is not reproducable.
I was also wondering why it is important for the `i-th` sample to know that it is the `i-th` sample. Maybe this parameter should be omitted in favor of an rng? I.e. let the user define `sampler(rng, tspan)` instead of `sampler(tspan, i)`.

<details>
  <summary>This is how the  current samplertype would look like</summary>
  
```julia
"""
    ContinousInputSampler{SF} <: AbstractInputSampler

Input sampler to create time continous inputs of the form `(t) -> input`.

    ContinousInputSampler(f, t_span; seed=1)

Create an input sampler based on sample function f.
- `f`: function with signature `(rng, tspan, i)` which returns a anonymous function
  `(t) -> input` which represents the input.
- `tspan`: can be used inside `f` to determine the input
- `seed`: optional seed the RNG
"""
mutable struct ContinousInputSampler{SF} <: AbstractInputSampler
    rng::MersenneTwister
    samplef::SF
    tspan::Tuple{Float64, Float64}
    _cache::Vector{Any}

    ContinousInputSampler(f, t_span; seed=1) = new{typeof(f)}(MersenneTwister(seed), f, t_span, Any[])
end

function Base.getindex(s::ContinuousInputSampler, idx)
    if idx > lastindex(s._cache)
        resize!(s._cache, idx)
        for i in lastindex(s._cache)+1:idx
            s._cache[i] = s.samplef(s.rng, s.t_span, i)
        end
    end
    return s._cache[idx]
end
```

</details>
<details>
  <summary>This is how the a new, constant input sampler could look like</summary>
  
```julia
"""
    ConstantInputSampler{SF} <: AbstractInputSampler

Input sampler to create constant inputs.

    ConstantInputSampler(f; seed=1)

Create an input sampler based on sample function f.
- `f`: function with signature `(rng, i)` which returns the input
- `seed`: optional seed the RNG
"""
mutable struct ConstantInputSampler{SF} <: AbstractInputSampler
    rng::MersenneTwister
    samplef::SF
    _cache::Vector{Any}

    ConstantInputSampler(f, t_span; seed=1) = new{typeof(f)}(MersenneTwister(seed), f, t_span, Any[])
end

function Base.getindex(s::ContinuousInputSampler, idx)
    if idx > lastindex(s._cache)
        resize!(s._cache, idx)
        for i in lastindex(s._cache)+1:idx
            s._cache[i] = s.samplef(s.rng, i)
        end
    end
    return s._cache[idx]
end
```

</details>

## the "old" problem type
With those definitions the current only problem type would become
```julia
"""
    RhsPBTProblem <: AbstractPBTProblem

Characterize problems by their rhs.

Arguments:
- `input_sampler`: `ContinousInputSampler`
- `p`: Problem parameters as `PBTProblemParameters`

- `f_spec`: Right hand side function of the system, called as f(dy, y, i, p, t).
- `f_sys`: Right hand side function of the specification, called as f(dy, y, i, p, t).
- `y0_spec`: Initial conditions for integrating the spec.
- `y0_sys`: Initial conditions for integrating the system.
- `tsteps`: Times are which to save the solution
- `t_span`: Start and end time of the integration
- `solver = Tsit5()`: Solver for integrating spec and system.
"""
struct RhsPBTProblem <: AbstractPBTProblem
    p::PBTProblemParameters
    input_sampler::ContinousInputSampler
    f_spec
    f_sys
    y0_spec
    y0_sys
    tsteps
    t_span
    solver = Tsit5()
end
```
The `solve_sys_spec` is allready defined for that

## possible new problem types
The above changes would allow us to create problems such as
```julia
struct MyPBTProblem <: AbsrtactPBTProlbem
    p::PBTProblemParameters
    input_sampler::ContinousInputSampler
    additional
end

function solve_sys_spec(pbt::MyPBTProblem, input, p_sys, p_spec)
    # do crazy stuff with high control over the `solve`, using callbacks,
    # have special initial conditions based on `pbt.additional` and so forth
    return (sol_sys, sol_spec)
end
```
which is basicially the whole point and would help for more complex systems which construct the ODEs based on the input using ND/PD and so forth.

Any comments or thoughts? @FHell @Anbue63 @antonplietzsch @e-zolotarevskaya

**Comment by AnnaBuettner** [comment]
Looks great! 
Regarding the input samples, what advantages do you see in providing a time-independent version? (Expect improved usability I mean!)

**Comment by hexaeder** [comment]
I don't know :D My main goal was to reduce the number of fields required in `AbstractPBTProblem`. Thats why I'd like to introduce a `InputSampler` type with the interface `sampler[i]` to get the `i`-th input.

And if we're introducing a new type anyway I think it's always worth to think about whether we want to make this an abstract interface rather than a concrete implementation. And it feels so inelegant do specify a `tspan` and an anonymous function when you're actually modelling a constant input..

Thats said I know I'm really bad with the [YAGNI](https://ronjeffries.com/xprog/articles/practices/pracnotneed/) principle ("Always implement things when you actually need them, never when you just foresee that you need them."), so maybe that's just overkill :D

**Comment by AnnaBuettner** [comment]
Haha :D 
I think we won't desperately need it because we can represent any input as a time series even if it is constant over `tspan`.
